Audit log fixes
JJConsulting/JJMasterData pull request #199
Opened 2024-02-22 21:26 UTC by gumbarros

2024-02-22 22:48 UTC, LucioPelinson commented on src/Core/DataManager/Services/FormService.cs
Inject class ExpressionsService can be removed

2024-02-22 22:56 UTC, LucioPelinson commented on src/Core/UI/Components/GridView/JJGridView.cs
> +        html.WithAttribute("id", Name);
Fire..... 0;)

2024-02-22 23:06 UTC, LucioPelinson approved these changes

2024-02-23 00:15 UTC, gumbarros commented on src/Core/UI/Components/GridView/JJGridView.cs
> +        html.WithAttribute("id", Name);
LGTM :)

2024-02-23 02:22 UTC, LucioPelinson requested changes
Review compilation

2024-02-23 14:43 UTC, LucioPelinson approved these changes

2024-02-23 14:49 UTC, LucioPelinson approved these changes

2024-02-23 14:52 UTC, merged