Add C# class source generation
JJConsulting/JJMasterData pull request #26
Opened 2022-09-26 18:27 UTC by ygorsilv1997

**PR Title**
C# class generator to be used with dictionary hashtable

**PR Description**
To convert the hashtable in your class you can use the "ToModel" extension of the hashtable.

2022-09-26 18:28 UTC, gumbarros commented on src/JJMasterData.Commons/Extensions/StringExtensions.cs
> +        /// Remove acentos da string
Maybe translate to English this comment?

2022-09-26 18:31 UTC, ygorsilv1997 commented on src/JJMasterData.Commons/Extensions/StringExtensions.cs
> +        /// Remove acentos da string
Adjusted

2022-09-26 18:35 UTC, LucioPelinson requested changes
Please remove class StringExtensions

2022-09-26 18:35 UTC, LucioPelinson commented on src/JJMasterData.Commons/Extensions/StringExtensions.cs
> +        public static string RemoveAccents(this string text)
This method already exists in StringManager.NoAccents.
Please avoid Extensions methods to string

2022-09-26 18:35 UTC, LucioPelinson commented on src/JJMasterData.Commons/Extensions/StringExtensions.cs
> +        public static string FirstCharToUpperComplete(this string input)
This method already exists in StringManager.FirstCharToUpper
Please remove this class

2022-09-27 12:08 UTC, gumbarros approved these changes

2022-09-27 12:08 UTC, gumbarros commented on src/JJMasterData.Commons/JJMasterData.Commons.csproj
> +	  <Compile Remove="Extensions\StringExtensions.cs" />
Please remove this <ItemGroup> from .csproj. The file does not exist.

2022-09-27 12:18 UTC, merged