36 saturn
JJConsulting/JJMasterData pull request #44
Opened 2022-11-04 02:34 UTC by LucioPelinson

#36

2022-11-04 02:41 UTC, gumbarros commented on src/JJMasterData.Api/Services/MasterApiService.cs
> +        var dataDictionaryManager = new FormService(formElement);
Don't forget to rename to formService :)

2022-11-10 00:28 UTC, LucioPelinson commented
Breaking changes
JJUploadFile event OnPostFile parameter JJFormFile was changed to another class called FormFileContent
JJDataImp OnAfterImport was removed now use OnAfterUpdate and OnAfterInsert

Bug fix:
Now the events:
	OnBeforeDelete;
	OnAfterDelete;
	OnBeforeInsert;
	OnAfterInsert;
	OnBeforeUpdate;
	OnAfterUpdate;
	OnBeforeImport;
are fired on API, Upload and form events;

2022-11-10 16:51 UTC, gumbarros requested changes

2022-11-10 16:51 UTC, gumbarros commented on src/JJMasterData.Core/DataManager/FormFileService.cs
> +        string fileFullName = FolderPath + file.FileName;
`Path.Combine(FolderPath, file.FileName)` is better because you don't know if FolderPath ends with / or not.

2022-11-10 16:51 UTC, gumbarros commented on src/JJMasterData.Core/DataManager/FormLetter.cs
> +    public int NumberOfRowsAffected { get; set; }
Nice

2022-11-10 16:51 UTC, gumbarros commented on src/JJMasterData.Core/DataManager/FormManager.cs
>          FormElement = formElement;
Add a 
```cs
if(FormElement == null)
    throw new ArgumentNullException(nameof(FormElement))
```
So you don't need to check if the FormElement is null in the entire class

2022-11-10 16:51 UTC, gumbarros commented on src/JJMasterData.Core/DataManager/FormManager.cs
> +        if (FormElement != null)
Is never null if we check in the `ctor`.

2022-11-10 17:05 UTC, gumbarros commented on src/JJMasterData.Core/DataManager/FormFileService.cs
> +            File.Delete(FolderPath + fileName);
Path.Combine

2022-11-10 17:39 UTC, merged